/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lingyiwanwu_descartes_GraphIndex */

#ifndef _Included_com_lingyiwanwu_descartes_GraphIndex
#define _Included_com_lingyiwanwu_descartes_GraphIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    addVectorInternal
 * Signature: ([BJJ)I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_addVectorInternal
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    searchInternal
 * Signature: ([BJLcom/lingyiwanwu/descartes/SearchContext;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_searchInternal
  (JNIEnv *, jobject, jbyteArray, jlong, jobject);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    refineIndex
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_refineIndex
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_close
  (JNIEnv *, jobject);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    dump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_dump
  (JNIEnv *, jobject);

/*
 * Class:     com_lingyiwanwu_descartes_GraphIndex
 * Method:    getCurrentDocCnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingyiwanwu_descartes_GraphIndex_getCurrentDocCnt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
